import type { Question } from "@/types/assessment";

export const QUESTIONS: Question[] = [
  { code: "SEC1", type: "likert", dimension: "security", reverse: true, required: true,
    text: "Even when I'm doing well financially, part of me worries that it could disappear." },
  { code: "SEC2", type: "likert", dimension: "security", required: true,
    text: "I trust my ability to recover from a major financial setback." },
  { code: "SEC3", type: "likert", dimension: "security", reverse: true, required: true,
    text: "Having substantially more money would make me feel substantially safer." },
  { code: "SEC4", type: "likert", dimension: "security", reverse: true, required: true,
    text: "I frequently think about what would happen if my income suddenly disappeared." },
  { code: "SEC5", type: "likert", dimension: "security", required: true,
    text: "Financial uncertainty can exist without taking up much of my mental attention." },
  { code: "SEC6", type: "likert", dimension: "security", required: true,
    text: "Whatever happens financially, I generally trust myself to figure it out." },

  { code: "ENO1", type: "likert", dimension: "enoughness", reverse: true, required: true,
    text: "When I reach an important financial goal, I'm usually thinking about the next one fairly quickly." },
  { code: "ENO2", type: "likert", dimension: "enoughness", required: true,
    text: "I can imagine becoming much wealthier without becoming significantly happier." },
  { code: "ENO3", type: "likert", dimension: "enoughness", reverse: true, required: true,
    text: "Seeing someone my age become significantly more successful can make my own accomplishments feel smaller." },
  { code: "ENO4", type: "likert", dimension: "enoughness", required: true,
    text: 'I have a reasonably clear idea of what "enough" money means for my life.' },
  { code: "ENO5", type: "likert", dimension: "enoughness", reverse: true, required: true,
    text: "There always seems to be another financial level that feels important to reach." },
  { code: "ENO6", type: "likert", dimension: "enoughness", required: true,
    text: "I could be deeply satisfied with my life even if my financial situation never dramatically improved from here." },

  { code: "IDN1", type: "likert", dimension: "identityAttachment", required: true,
    text: "My financial accomplishments are an important part of how I think about myself." },
  { code: "IDN2", type: "likert", dimension: "identityAttachment", required: true,
    text: "If my net worth fell dramatically, I would probably feel less successful as a person." },
  { code: "IDN3", type: "likert", dimension: "identityAttachment", required: true,
    text: "Making more money makes me feel more competent." },
  { code: "IDN4", type: "likert", dimension: "identityAttachment", required: true,
    text: "I would find it difficult to watch my peers become much more financially successful than me." },
  { code: "IDN5", type: "likert", dimension: "identityAttachment", reverse: true, required: true,
    text: "I believe I'd have essentially the same worth as a person if I lost most of what I've built." },
  { code: "IDN6", type: "likert", dimension: "identityAttachment", required: true,
    text: "If nobody knew how financially successful I was, it would meaningfully reduce some of the satisfaction." },

  { code: "CTL1", type: "likert", dimension: "control", required: true,
    text: "I feel most comfortable financially when I understand exactly where things are headed." },
  { code: "CTL2", type: "likert", dimension: "control", required: true,
    text: "Unexpected expenses bother me even when I can comfortably afford them." },
  { code: "CTL3", type: "likert", dimension: "control", reverse: true, required: true,
    text: "I can make a major financial decision without needing to know how everything will turn out." },
  { code: "CTL4", type: "likert", dimension: "control", required: true,
    text: "I spend significant mental energy trying to optimize financial decisions." },
  { code: "CTL5", type: "likert", dimension: "control", required: true,
    text: "When something changes financially, my instinct is to immediately figure out what to do about it." },
  { code: "CTL6", type: "likert", dimension: "control", reverse: true, required: true,
    text: "I'm comfortable leaving some financial questions unresolved." },

  { code: "FRE1", type: "likert", dimension: "freedom", required: true,
    text: "The most valuable thing money can buy is control over my time." },
  { code: "FRE2", type: "likert", dimension: "freedom", required: true,
    text: "I would accept substantially less income for substantially more autonomy." },
  { code: "FRE3", type: "likert", dimension: "freedom", required: true,
    text: "Being financially dependent on another person or organization would be particularly uncomfortable for me." },
  { code: "FRE4", type: "likert", dimension: "freedom", required: true,
    text: "The ability to walk away from something matters more to me than owning expensive things." },
  { code: "FRE5", type: "likert", dimension: "freedom", required: true,
    text: "I think about wealth primarily in terms of what it allows me to do rather than what it allows me to own." },
  { code: "FRE6", type: "likert", dimension: "freedom", required: true,
    text: "Having commitments that require me to maintain a certain income makes me uncomfortable." },

  { code: "PRE1", type: "likert", dimension: "presence", reverse: true, required: true,
    text: "I sometimes postpone things I would enjoy even though I can reasonably afford them." },
  { code: "PRE2", type: "likert", dimension: "presence", required: true,
    text: "Once I've decided I can afford something, I can usually enjoy spending the money without guilt." },
  { code: "PRE3", type: "likert", dimension: "presence", reverse: true, required: true,
    text: "It's difficult for me to stop thinking about financial goals when I'm supposed to be relaxing." },
  { code: "PRE4", type: "likert", dimension: "presence", required: true,
    text: "Some financial optimization is worth sacrificing in order to enjoy life now." },
  { code: "PRE5", type: "likert", dimension: "presence", reverse: true, required: true,
    text: "I sometimes tell myself I'll relax more after reaching the next financial milestone." },
  { code: "PRE6", type: "likert", dimension: "presence", required: true,
    text: "I regularly experience the benefits of the money I've already earned." },

  { code: "ATT1", type: "likert", required: true,
    text: "I enjoy thinking about investments, businesses, financial opportunities, or ways to build wealth." },
  { code: "ATT2", type: "likert", required: true,
    text: "Thinking about money is intellectually interesting to me." },
  { code: "ATT3", type: "likert", required: true,
    text: "Money occupies more of my mental attention than I would ideally like." },
  { code: "ATT4", type: "likert", required: true,
    text: "Even when I want to stop thinking about money or work, I sometimes find it difficult." },

  { code: "SCN1", type: "single_choice", required: true,
    text: "You unexpectedly receive $25,000 after taxes and don't immediately need the money. What thought appears first?",
    options: [
      {id:"A", text:"How should I invest it?"},
      {id:"B", text:"I should put this somewhere safe."},
      {id:"C", text:"What could I experience with some of this?"},
      {id:"D", text:"Could I use this to create more income?"},
      {id:"E", text:"This gives me more breathing room."},
      {id:"F", text:"I should reduce an obligation."}
    ]},
  { code: "SCN2", type: "single_choice", required: true,
    text: "You're guaranteed enough money to live comfortably for life, but you'll never become significantly wealthier than you are today. How does that feel?",
    options: [
      {id:"A", text:"Extremely relieving"},
      {id:"B", text:"Mostly relieving"},
      {id:"C", text:"Neutral"},
      {id:"D", text:"Somewhat uncomfortable"},
      {id:"E", text:"Extremely uncomfortable"}
    ]},
  { code: "SCN3", type: "single_choice", required: true,
    text: "Your net worth falls 20%, but your lifestyle and current income are unchanged. What's closest to your reaction?",
    options: [
      {id:"A", text:"I'd have trouble thinking about much else."},
      {id:"B", text:"I'd immediately develop a recovery plan."},
      {id:"C", text:"I'd be frustrated, but my life wouldn't meaningfully change."},
      {id:"D", text:"I'd mostly accept that wealth fluctuates."},
      {id:"E", text:"It depends why it happened."}
    ]},
  { code: "SCN4", type: "single_choice", required: true,
    text: "A close friend who previously earned less than you becomes worth $20 million. What's closest to your immediate reaction?",
    options: [
      {id:"A", text:"I'm genuinely excited for them."},
      {id:"B", text:"I'm excited, but I'd compare myself somewhat."},
      {id:"C", text:"It would make me wonder whether I'm thinking big enough."},
      {id:"D", text:"I'd feel like I was falling behind."},
      {id:"E", text:"It wouldn't meaningfully change how I view my own success."}
    ]},
  { code: "SCN5", type: "single_choice", required: true,
    text: "You unexpectedly get an entire Friday with nothing you need to do. Which sounds most appealing?",
    options: [
      {id:"A", text:"Work on something I've wanted to build."},
      {id:"B", text:"Review investments, finances, or opportunities."},
      {id:"C", text:"Spend the day with people I care about."},
      {id:"D", text:"Go somewhere or do something fun."},
      {id:"E", text:"Do nothing productive."},
      {id:"F", text:"I'd probably end up working anyway."}
    ]},
  { code: "SCN6", type: "single_choice", required: true,
    text: "Your after-tax income permanently increases by $100,000 per year. What feels most natural?",
    options: [
      {id:"A", text:"Invest almost all of it."},
      {id:"B", text:"Upgrade somewhat and invest the majority."},
      {id:"C", text:"Significantly improve my lifestyle."},
      {id:"D", text:"Use it to reduce how much I need to work."},
      {id:"E", text:"Use it to pursue new opportunities or businesses."},
      {id:"F", text:"Build a larger safety cushion."}
    ]},
  { code: "SCN7", type: "single_choice", required: true,
    text: "You reach the financial number you've been working toward for years. What is most likely to happen?",
    options: [
      {id:"A", text:"I'd feel like I'd made it."},
      {id:"B", text:"I'd enjoy it for a while, then set another goal."},
      {id:"C", text:"I'd immediately start thinking bigger."},
      {id:"D", text:"I'd seriously reduce how much I work."},
      {id:"E", text:"I don't actually have a finish line."}
    ]},
  { code: "SCN8", type: "single_choice", required: true,
    text: "Assume both are equally secure. Which would you choose?",
    options: [
      {id:"A", text:"$500,000/year working 50 hours/week"},
      {id:"B", text:"$200,000/year working 15 hours/week"}
    ]},
  { code: "SCN8B", type: "single_choice", required: true,
    text: "What if the 50-hour option paid $1,000,000/year?",
    options: [
      {id:"A", text:"$1,000,000/year working 50 hours/week"},
      {id:"B", text:"$200,000/year working 15 hours/week"}
    ]},

  { code: "FIN1", type: "financial_context", required: false,
    text: "What is your approximate household income range?" },
  { code: "FIN2", type: "financial_context", required: false,
    text: "What is your approximate household net worth range?" },
  { code: "FIN3", type: "financial_context", required: false,
    text: "If your household lost all income tomorrow, how long could you maintain your current lifestyle?" },
  { code: "FIN4", type: "financial_context", required: false,
    text: "How burdensome do your current debt payments and fixed financial obligations feel relative to your income?" },
  { code: "REF1", type: "free_text", required: false,
    text: "If you woke up tomorrow and knew with absolute certainty that you already had enough, what—if anything—would you change about the way you're living today?" },
];
